"""subscription: cancel_at_period_end

Revision ID: 7f9032c8a14d
Revises: cbc158286604
Create Date: 2026-09-28 16:55:46.740508

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7f9032c8a14d"
down_revision = "cbc158286604"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "cancel_at_period_end", sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )

    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.alter_column("cancel_at_period_end", server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.drop_column("cancel_at_period_end")

    # ### end Alembic commands ###
