"""subscription: amount + ends_at

Revision ID: cbc158286604
Revises: f16d77d49c15
Create Date: 2026-09-28 16:46:45.390063

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cbc158286604"
down_revision = "f16d77d49c15"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscription_plans", schema=None) as batch_op:
        batch_op.add_column(sa.Column("amount", sa.Integer(), nullable=False, server_default="0"))

    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###

    # Backfill числовой цены для уже засеянных тарифов (`seed.py` пропускает
    # повторный сид, если демо-пользователь уже есть — новые `amount` из
    # PLANS_SEED в существующую базу иначе не попадут).
    plans_table = sa.table(
        "subscription_plans", sa.column("id", sa.String), sa.column("amount", sa.Integer)
    )
    op.execute(plans_table.update().where(plans_table.c.id == "week").values(amount=500))
    op.execute(plans_table.update().where(plans_table.c.id == "month").values(amount=1900))

    with op.batch_alter_table("subscription_plans", schema=None) as batch_op:
        batch_op.alter_column("amount", server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.drop_column("ends_at")

    with op.batch_alter_table("subscription_plans", schema=None) as batch_op:
        batch_op.drop_column("amount")

    # ### end Alembic commands ###
