"""university matching fields

Revision ID: cda290b5384e
Revises: 7f9032c8a14d
Create Date: 2026-10-01 17:22:55.462601

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cda290b5384e"
down_revision = "7f9032c8a14d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default на NOT NULL колонках — чтобы миграция не падала на уже
    # засеянных строках `universities` (бэкфилл реальных значений — через
    # `seed.py`, который пересевает каталог целиком).
    with op.batch_alter_table("universities", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("country", sa.String(length=64), nullable=False, server_default="")
        )
        batch_op.add_column(sa.Column("faculties", sa.JSON(), nullable=False, server_default="[]"))
        batch_op.add_column(
            sa.Column("languages_offered", sa.JSON(), nullable=False, server_default="[]")
        )
        batch_op.add_column(
            sa.Column("tuition_eur_per_year", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(sa.Column("scholarship_coverage_pct", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("selectivity_tier", sa.Integer(), nullable=False, server_default="3")
        )
        batch_op.add_column(
            sa.Column("required_gpa_index", sa.Integer(), nullable=False, server_default="50")
        )
        batch_op.add_column(
            sa.Column(
                "required_profile_score_index",
                sa.Integer(),
                nullable=False,
                server_default="50",
            )
        )
        batch_op.add_column(
            sa.Column("required_language_index", sa.Integer(), nullable=False, server_default="50")
        )

    with op.batch_alter_table("universities", schema=None) as batch_op:
        for column in (
            "country",
            "faculties",
            "languages_offered",
            "tuition_eur_per_year",
            "selectivity_tier",
            "required_gpa_index",
            "required_profile_score_index",
            "required_language_index",
        ):
            batch_op.alter_column(column, server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("universities", schema=None) as batch_op:
        batch_op.drop_column("required_language_index")
        batch_op.drop_column("required_profile_score_index")
        batch_op.drop_column("required_gpa_index")
        batch_op.drop_column("selectivity_tier")
        batch_op.drop_column("scholarship_coverage_pct")
        batch_op.drop_column("tuition_eur_per_year")
        batch_op.drop_column("languages_offered")
        batch_op.drop_column("faculties")
        batch_op.drop_column("country")

    # ### end Alembic commands ###
